/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment;

import assignment.database.DatabaseInitializer;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) throws Exception {
    System.out.println(new App().getGreeting());
    DatabaseInitializer.initialize();
  }
}
