/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    assertTrue(true);
  }
}
