/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    // Spotless formatter plugin, latest version as of 14th May 2025
    id("com.diffplug.spotless") version "8.4.0"
}   

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // Apache Derby (Embedded)
    implementation("org.apache.derby:derby:10.17.1.0")

    // Apache Derby (Remote)
    implementation("org.apache.derby:derbyclient:10.17.1.0")

    // Apache Derby (Server)
    implementation("org.apache.derby:derbynet:10.17.1.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.register<JavaExec>("startDerbyServer") {
    group = "database"
    description = "Starts the Apache Derby Network Server."
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass.set("org.apache.derby.drda.NetworkServerControl")
    args("start", "-h", "localhost", "-p", "1527")
}

application {
    // Define the main class for the application.
    mainClass = "assignment.App"
}

spotless {
    java {
        // Uses the Google Java Style
        googleJavaFormat() 
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
